@WarehouseWebAPI_HostAddress = https://localhost:7180

GET {{WarehouseWebAPI_HostAddress}}/api/companies

###

POST {{WarehouseWebAPI_HostAddress}}/api/companies
Content-Type: application/json

{

  "companyName": "Tools R' Us",
    "address": "5555 Main St",
    "city": "Detroit",
    "state": "Michigan",
    "postalCode": "55443",
    "orders": []
}

###

GET {{WarehouseWebAPI_HostAddress}}/api/managers

###

GET {{WarehouseWebAPI_HostAddress}}/api/managers

###

POST {{WarehouseWebAPI_HostAddress}}/api/orders
Content-Type: application/json

{
  "OrderDate": "2023-08-20T00:00:00",
    "CompanyId": "1",
    "OrderItems": []
}

###

GET {{WarehouseWebAPI_HostAddress}}/api/orders

###
